image: its-registry.unl.edu/hcc/docker-ood-builder:latest

stages:
  - build

rpm-build:
  stage: build
  tags:
    - docker
  script:
    - make rpm
  artifacts:
    paths:
      - .artifacts/
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_TAG"
